REALIZAR UN PROHRAMA QUE CUM,PLA CPN LO SIGUIENTE
.CONDICIONAL DE ARRANQUE
-FUNCION MAIN O RUN
-MODULOS LOCALES
-ALGUN MODULO O PAQUETE DE PIP

EL PROGRAMA ES LIBRE. ALGUNOS EJEMPLOS:
-CALCULADORA (tradicional, temperatura, pes, conversion de moneda,)
-INVENTARIOS
-BOLSA AZAR
-CRONOMETRO